package sem

// inventoryLanguageExtensions is the explicit inventory-support tier. These
// filetypes are recognized deterministically and emit stable document symbols,
// but they do not claim rich language-aware relation extraction.
var inventoryLanguageExtensions = map[string]languageSpec{
	".4th":         {language: "Forth", inventoryOnly: true},
	".abap":        {language: "ABAP", inventoryOnly: true},
	".agda":        {language: "Agda", inventoryOnly: true},
	".ahk":         {language: "AutoHotkey", inventoryOnly: true},
	".applescript": {language: "AppleScript", inventoryOnly: true},
	".as":          {language: "ActionScript", inventoryOnly: true},
	".asm":         {language: "Assembly", inventoryOnly: true},
	".astro":       {language: "Astro", inventoryOnly: true},
	".aug":         {language: "Augeas", inventoryOnly: true},
	".awk":         {language: "Awk", inventoryOnly: true},
	".bal":         {language: "Ballerina", inventoryOnly: true},
	".bas":         {language: "BASIC", inventoryOnly: true},
	".bf":          {language: "Brainfuck", inventoryOnly: true},
	".bib":         {language: "BibTeX", inventoryOnly: true},
	".bicep":       {language: "Bicep", inventoryOnly: true},
	".blade.php":   {language: "Blade", inventoryOnly: true},
	".bnf":         {language: "BNF", inventoryOnly: true},
	".boo":         {language: "Boo", inventoryOnly: true},
	".bzl":         {language: "Starlark", inventoryOnly: true},
	".cabal":       {language: "Cabal", inventoryOnly: true},
	".ceylon":      {language: "Ceylon", inventoryOnly: true},
	".cfm":         {language: "ColdFusion", inventoryOnly: true},
	".cmake":       {language: "CMake", inventoryOnly: true},
	".cob":         {language: "COBOL", inventoryOnly: true},
	".coffee":      {language: "CoffeeScript", inventoryOnly: true},
	".coq":         {language: "Coq", inventoryOnly: true},
	".cr":          {language: "Crystal", inventoryOnly: true},
	".csproj":      {language: "MSBuild Project", inventoryOnly: true},
	".d":           {language: "D", inventoryOnly: true},
	".dhall":       {language: "Dhall", inventoryOnly: true},
	".diff":        {language: "Diff", inventoryOnly: true},
	".dm":          {language: "DM", inventoryOnly: true},
	".dtd":         {language: "DTD", inventoryOnly: true},
	".dylan":       {language: "Dylan", inventoryOnly: true},
	".e":           {language: "Eiffel", inventoryOnly: true},
	".ecl":         {language: "ECL", inventoryOnly: true},
	".elm":         {language: "Elm", inventoryOnly: true},
	".erb":         {language: "ERB", inventoryOnly: true},
	".factor":      {language: "Factor", inventoryOnly: true},
	".fan":         {language: "Fantom", inventoryOnly: true},
	".fish":        {language: "Fish", inventoryOnly: true},
	".frag":        {language: "GLSL", inventoryOnly: true},
	".fs":          {language: "F#", inventoryOnly: true},
	".fsi":         {language: "F#", inventoryOnly: true},
	".fsscript":    {language: "F#", inventoryOnly: true},
	".fsx":         {language: "F#", inventoryOnly: true},
	".g4":          {language: "ANTLR", inventoryOnly: true},
	".gd":          {language: "GDScript", inventoryOnly: true},
	".gdb":         {language: "GDB", inventoryOnly: true},
	".gemspec":     {language: "RubyGems", inventoryOnly: true},
	".glsl":        {language: "GLSL", inventoryOnly: true},
	".gml":         {language: "GameMaker Language", inventoryOnly: true},
	".gnuplot":     {language: "Gnuplot", inventoryOnly: true},
	".graphql":     {language: "GraphQL", inventoryOnly: true},
	".graphqls":    {language: "GraphQL", inventoryOnly: true},
	".hack":        {language: "Hack", inventoryOnly: true},
	".haml":        {language: "Haml", inventoryOnly: true},
	".handlebars":  {language: "Handlebars", inventoryOnly: true},
	".idr":         {language: "Idris", inventoryOnly: true},
	".ini":         {language: "INI", inventoryOnly: true},
	".ino":         {language: "Arduino", inventoryOnly: true},
	".io":          {language: "Io", inventoryOnly: true},
	".j2":          {language: "Jinja", inventoryOnly: true},
	".jade":        {language: "Pug", inventoryOnly: true},
	".jq":          {language: "jq", inventoryOnly: true},
	".jsp":         {language: "JSP", inventoryOnly: true},
	".jlisp":       {language: "Lisp", inventoryOnly: true},
	".lean":        {language: "Lean", inventoryOnly: true},
	".less":        {language: "Less", inventoryOnly: true},
	".lidr":        {language: "Idris", inventoryOnly: true},
	".lisp":        {language: "Common Lisp", inventoryOnly: true},
	".ll":          {language: "LLVM", inventoryOnly: true},
	".ls":          {language: "LiveScript", inventoryOnly: true},
	".m4":          {language: "M4", inventoryOnly: true},
	".matlab":      {language: "MATLAB", inventoryOnly: true},
	".mm":          {language: "Objective-C++", inventoryOnly: true},
	".mcfunction":  {language: "MCFunction", inventoryOnly: true},
	".mermaid":     {language: "Mermaid", inventoryOnly: true},
	".metal":       {language: "Metal", inventoryOnly: true},
	".mint":        {language: "Mint", inventoryOnly: true},
	".moon":        {language: "MoonScript", inventoryOnly: true},
	".mustache":    {language: "Mustache", inventoryOnly: true},
	".nim":         {language: "Nim", inventoryOnly: true},
	".nix":         {language: "Nix", inventoryOnly: true},
	".nu":          {language: "Nu", inventoryOnly: true},
	".p8":          {language: "Pico-8", inventoryOnly: true},
	".pas":         {language: "Pascal", inventoryOnly: true},
	".patch":       {language: "Patch", inventoryOnly: true},
	".pde":         {language: "Processing", inventoryOnly: true},
	".plist":       {language: "Property List", inventoryOnly: true},
	".pony":        {language: "Pony", inventoryOnly: true},
	".pp":          {language: "Puppet", inventoryOnly: true},
	".purs":        {language: "PureScript", inventoryOnly: true},
	".racket":      {language: "Racket", inventoryOnly: true},
	".raku":        {language: "Raku", inventoryOnly: true},
	".razor":       {language: "Razor", inventoryOnly: true},
	".re":          {language: "Reason", inventoryOnly: true},
	".rego":        {language: "Rego", inventoryOnly: true},
	".res":         {language: "ReScript", inventoryOnly: true},
	".rkt":         {language: "Racket", inventoryOnly: true},
	".ron":         {language: "RON", inventoryOnly: true},
	".rst":         {language: "reStructuredText", inventoryOnly: true},
	".sas":         {language: "SAS", inventoryOnly: true},
	".sass":        {language: "Sass", inventoryOnly: true},
	".scad":        {language: "OpenSCAD", inventoryOnly: true},
	".scheme":      {language: "Scheme", inventoryOnly: true},
	".scss":        {language: "SCSS", inventoryOnly: true},
	".sed":         {language: "sed", inventoryOnly: true},
	".shader":      {language: "ShaderLab", inventoryOnly: true},
	".slim":        {language: "Slim", inventoryOnly: true},
	".sol":         {language: "Solidity", inventoryOnly: true},
	".sparql":      {language: "SPARQL", inventoryOnly: true},
	".sqf":         {language: "SQF", inventoryOnly: true},
	".sre":         {language: "SRecode Template", inventoryOnly: true},
	".stan":        {language: "Stan", inventoryOnly: true},
	".styl":        {language: "Stylus", inventoryOnly: true},
	".tcl":         {language: "Tcl", inventoryOnly: true},
	".tex":         {language: "TeX", inventoryOnly: true},
	".textile":     {language: "Textile", inventoryOnly: true},
	".thrift":      {language: "Thrift", inventoryOnly: true},
	".twig":        {language: "Twig", inventoryOnly: true},
	".v":           {language: "V", inventoryOnly: true},
	".vala":        {language: "Vala", inventoryOnly: true},
	".vb":          {language: "Visual Basic .NET", inventoryOnly: true},
	".vcl":         {language: "VCL", inventoryOnly: true},
	".vhdl":        {language: "VHDL", inventoryOnly: true},
	".vim":         {language: "Vim Script", inventoryOnly: true},
	".vuepress":    {language: "VuePress", inventoryOnly: true},
	".wat":         {language: "WebAssembly", inventoryOnly: true},
	".wl":          {language: "Wolfram Language", inventoryOnly: true},
	".wren":        {language: "Wren", inventoryOnly: true},
	".xquery":      {language: "XQuery", inventoryOnly: true},
	".xslt":        {language: "XSLT", inventoryOnly: true},
	".xtend":       {language: "Xtend", inventoryOnly: true},
	".zimpl":       {language: "Zimpl", inventoryOnly: true},
}

var inventoryLanguageFilenames = map[string]languageSpec{
	".babelrc":         {language: "Babel Config", inventoryOnly: true},
	".editorconfig":    {language: "EditorConfig", inventoryOnly: true},
	".env":             {language: "Dotenv", inventoryOnly: true},
	".gitignore":       {language: "Git Ignore", inventoryOnly: true},
	".npmrc":           {language: "NPM Config", inventoryOnly: true},
	"brewfile":         {language: "Homebrew Bundle", inventoryOnly: true},
	"cmakelists.txt":   {language: "CMake", inventoryOnly: true},
	"gemfile":          {language: "Bundler", inventoryOnly: true},
	"justfile":         {language: "Just", inventoryOnly: true},
	"rakefile":         {language: "Rake", inventoryOnly: true},
	"requirements.txt": {language: "Pip Requirements", inventoryOnly: true},
}
